### ISSUE TITLE
Colab Demo Notebook for JaxADi

### ISSUE THREAD

**Issue by simeon-ned** [based-robotics/jaxadi#11]
I would like to suggest a Google Colab demo for `jaxadi`, which transforms CasADi functions into batchable JAX-compatible functions. This will showcase:

1. Setup and installation.
2. Step-by-step usage of `jaxadi`.
3. Example inputs and outputs.
4. Key features and customization.

**Benefits:**

- Easy experimentation in an interactive environment.
- Accessibility on CPUs, GPUs, and TPUs.

**Comment by SAMBILI** [comment]
I think this will help you.
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
